# Generated by Django 6.0.1 on 2026-01-13 05:08

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Kanji',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('character', models.CharField(max_length=10)),
                ('reading', models.CharField(max_length=50)),
                ('meaning', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='UserKanji',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(choices=[('known', 'Known'), ('unknown', 'Unknown')], max_length=10)),
                ('saved', models.BooleanField(default=False)),
                ('kanji', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='flashcards.kanji')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
