# Generated by Django 6.0.1 on 2026-01-14 01:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('flashcards', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='kanji',
            name='level',
            field=models.CharField(default='N5', max_length=10),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='kanji',
            name='reading',
            field=models.CharField(max_length=100),
        ),
    ]
