# Generated by Django 6.0.1 on 2026-01-27 05:19

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('flashcards', '0004_profile'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Grammar',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('level', models.CharField(choices=[('N5', 'N5'), ('N4', 'N4'), ('N3', 'N3'), ('N2', 'N2')], max_length=2)),
                ('number', models.IntegerField()),
                ('pattern', models.CharField(max_length=100)),
                ('meaning_jp', models.TextField()),
                ('meaning_en', models.TextField()),
                ('example_jp', models.TextField()),
                ('example_en', models.TextField()),
                ('structure', models.TextField(blank=True)),
                ('notes', models.TextField(blank=True)),
                ('saved_by', models.ManyToManyField(blank=True, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
