# Generated by Django 6.0.1 on 2026-01-28 07:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('flashcards', '0005_grammar'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='grammar',
            name='number',
        ),
    ]
