# Generated by Django 6.0.1 on 2026-01-29 01:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('flashcards', '0006_remove_grammar_number'),
    ]

    operations = [
        migrations.AlterField(
            model_name='grammar',
            name='level',
            field=models.CharField(choices=[('N5', 'N5'), ('N4', 'N4'), ('N3', 'N3'), ('N2', 'N2')], max_length=5),
        ),
    ]
