# Generated by Django 6.0.1 on 2026-02-11 17:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('flashcards', '0007_alter_grammar_level'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='bio',
            field=models.CharField(blank=True, max_length=150),
        ),
    ]
