# Generated by Django 6.0.1 on 2026-02-12 01:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('flashcards', '0008_profile_bio'),
    ]

    operations = [
        migrations.CreateModel(
            name='Conversation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('category', models.CharField(max_length=100)),
                ('japanese', models.CharField(max_length=255)),
                ('hiragana', models.CharField(max_length=255)),
                ('meaning', models.CharField(max_length=255)),
            ],
        ),
    ]
